# Generated by Django 2.2.5 on 2019-09-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeReferenceModel',
            fields=[
                ('statusCode', models.IntegerField(help_text='Primary key Unique identifier', primary_key=True, serialize=False)),
                ('description', models.CharField(help_text='Verbose description related to the StatusCode', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('taskID', models.AutoField(help_text='Linear record counter', primary_key=True, serialize=False)),
                ('customerCode', models.CharField(help_text='Primary key uniquely identifying', max_length=50)),
                ('custFirstName', models.CharField(help_text='customerApp firstname', max_length=100)),
                ('custLastname', models.CharField(help_text='customerApp lastname', max_length=100)),
                ('deliveryaddress', models.CharField(help_text='Delivery address on the customer', max_length=100)),
                ('statusCode', models.CharField(help_text='Reference code to status of order/delivery', max_length=100)),
                ('statusDescription', models.CharField(help_text='A verbose description of the status referenced', max_length=100)),
            ],
        ),
    ]
