# Generated by Django 2.2.5 on 2019-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_codereference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('taskID', models.AutoField(help_text='Linear record counter', primary_key=True, serialize=False)),
                ('customerCode', models.CharField(help_text='Primary key uniquely identifying each customer', max_length=50)),
                ('custFirstName', models.CharField(help_text='customer firstname', max_length=100)),
                ('custLastname', models.CharField(help_text='customer lastname', max_length=100)),
                ('deliveryaddress', models.CharField(help_text='Delivery address on the customerApp', max_length=100)),
                ('statusCode', models.CharField(help_text='Reference code to status of  order/delivery', max_length=100)),
                ('statusDescription', models.CharField(help_text='A verbose description of the status referenced from the Table/field: CodeReference/Description.', max_length=100)),
            ],
        ),
    ]
