# Generated by Django 2.0.1 on 2019-09-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='programmer',
            name='languages',
        ),
        migrations.AlterField(
            model_name='customer',
            name='custFirstName',
            field=models.CharField(help_text='customer firstname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='custLastname',
            field=models.CharField(help_text='customer lastname', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(help_text='Primary key uniquely identifying each customer', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='deliveryaddress',
            field=models.CharField(help_text='Delivery address on the customerApp', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='statusCode',
            field=models.CharField(help_text='Reference code to status of  order/delivery', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='statusDescription',
            field=models.CharField(help_text='A verbose description of the status referenced from the Table/field: CodeReference/Description.', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
