# Generated by Django 2.0.1 on 2019-09-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20190926_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customerCode',
            field=models.CharField(help_text='Primary key uniquely identifying each customer', max_length=50, null=True),
        ),
    ]
